name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 mins

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/tra-vaye/travaye-frontend
          git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main 

      - name: Push changes to fork
        run: git push origin main  
